sudo: required
dist: bionic

# We first need to install an ancient GCC to compile GTest and GMock, then we are able to upgrade GCC-8
before_install:
    - sudo apt-get update -y -q
    - sudo apt-get install -y build-essential libgtest-dev cmake google-mock
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - cd /usr/src/gmock
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - sudo ldconfig
    - cd $TRAVIS_BUILD_DIR
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -y -q
    - sudo apt-get install gcc-8 g++-8 libgtkmm-3.0-dev libgstreamermm-1.0-dev libasan5
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8

script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j8
    - cd ..
    - ./build/Tests --gtest_repeat=10 --gtest_shuffle --gtest_color=yes

