sudo: required
dist: bionic

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -y -q
    - sudo apt-get install -y libgtest-dev cmake valgrind gcc-8 g++-8 libasan5 libgtk-3-dev libgtkmm-3.0-dev google-mock
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - cd /usr/src/gmock
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - sudo ldconfig
    - cd $TRAVIS_BUILD_DIR

script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j8
    - cd ..
    - ./build/Tests --gtest_repeat=10 --gtest_shuffle --gtest_color=yes

